import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers"
import ToastConfigured from "@/components/toast-conf";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head />
    <body>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}        
        <ToastConfigured />
      </ThemeProvider>
    </body>
  </html>
  );
}
